### ISSUE TITLE
Better instalation section

### ISSUE THREAD

**Issue by lfarah** [PhilippeBoisney/ModernSearchBar#11]
Hey, your library is really interesting.

The only problem I found was the ```README.md```, which has an incomplete ```Installation Section```
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to easily create a complete ```Installation Section```
If you want, I can help you to organize the lib.

What are your thoughts? 😄

**Comment by lfarah** [comment]
Please fix this issue before we can merge [your PR in AwesomeiOS](https://github.com/vsouza/awesome-ios/pull/1536)

**Comment by PhilippeBoisney** [comment]
Thanks @lfarah ! I fixed it. Hope everything is going well for you ;)
