### ISSUE TITLE
Swift 2.3 Code

### ISSUE THREAD

**Issue by manjitsinghbhullar** [PhilippeBoisney/ModernSearchBar#15]
Can you provide the same code in swift 2.3 . I need to implement in swift 2.3

**Comment by PhilippeBoisney** [comment]
I can't maintain two version of this library. However, you can convert [all those classes](https://github.com/PhilippeBoisney/ModernSearchBar/tree/master/Pod/Classes) in swift 2.3 with xCode automatically if you want to implement ModernSearchBar in your project. Don't forget to import the assets too.

**Comment by manjitsinghbhullar** [comment]
I convert all the code to swift 2.3 it showing me a error of 'ModernSearchBar' does not conform to protocol 'UITableViewDataSource' I send you a email please see the converted file.
