### ISSUE TITLE
Using Firebase

### ISSUE THREAD

**Issue by rlee1990** [PhilippeBoisney/ModernSearchBar#16]
Hi trying to use this with Firebase. I am using the withURL option but nothing shows when i search. The data is pulling from firebase.

**Comment by PhilippeBoisney** [comment]
You have to first fetch all datas from firebase, then when all your datas are downloaded, you can use **"setDatasWithUrl(datas: your_url_list)"**

**Comment by rlee1990** [comment]
I have done all of that i even printed the data to make sure it was coming through and it was. Just doesn't show in the search.

**Comment by PhilippeBoisney** [comment]
Can you provide some examples with code ?

**Comment by rlee1990** [comment]
I had my code like this
ref.queryOrdered(byChild: "firstName").observe(.childAdded, with: { (snapshot) in
            
            self.usersArray.append((snapshot.value as? NSDictionary)!)
            print("Rickey: \(self.usersArray)")

and suggestionListWithUrl.append(ModernSearchBarModel(title: usersArray["firstName"], url: usersArray["profilePic"]

**Comment by rlee1990** [comment]
Not sure if i was doing something wrong. Still only a few months in with Swift.
